<#assign ctx=request.contextPath/>
<!DOCTYPE html>
<html lang="en">

<link rel="stylesheet" href="${ctx!}/web-static/css/test.css">
<body>
<div id="To">
    <div id="S1">
        <div id="S2">
<form>
    <table>
        <thead>
        <tr>
            <th>姓名</th>
            <th>电话</th>
            <th>年龄</th>
            <th>性别</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
            <tr>
                <td>许杰</td>
                <td>15465412589</td>
                <td>89</td>
                <td>男</td>
            </tr>
        </tbody>
    </table>
</form>
        </div>
    </div>
</div>
</body>
</html>
